version: '2.1'
services:

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: styxco/ecgw-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"